probot_anno:
  arm_joint_controller:
    type: "position_controllers/JointTrajectoryController"
    joints:
      - robot_joint1
      - robot_joint2
      - robot_joint3
      - robot_joint4
      - robot_joint5
      - robot_joint6


    gains:
      robot_joint1:   {p: 1000.0, i: 0.0, d: 0.1, i_clamp: 0.0}
      robot_joint2:   {p: 1000.0, i: 0.0, d: 0.1, i_clamp: 0.0}
      robot_joint3:   {p: 1000.0, i: 0.0, d: 0.1, i_clamp: 0.0}
      robot_joint4:   {p: 1000.0, i: 0.0, d: 0.1, i_clamp: 0.0}
      robot_joint5:   {p: 1000.0, i: 0.0, d: 0.1, i_clamp: 0.0}
      robot_joint6:   {p: 1000.0, i: 0.0, d: 0.1, i_clamp: 0.0}




